ndelvalle/v-click-outside

lib/v-click-outside.js
There are times when it's not enough to know that you clicked outside an element, but you also want to know what got clicked outside. Rather than have two listeners, it would be nice to just get the click event from the click-outside event.
=> Added click event to callback.

lib/v-click-outside.js, test/v-click-outside.test.js
The previous version was not working with multiple use of v-click-outside. This fix this by keeping a reference to all binded elements and registering only one listener.
If you unbind all elements, the listener is automatically removed.
=> Allow multiple v-click-outside to be used with one listener

lib/v-click-outside.js
@ndelvalle first of all thanks for great lib!
There is one issue where iPhone/iPad is not triggering 'click' event that is fixed with this PR as for iPhone and iPad we are now listening for touchstart event not click event. 
You can find more info about issue [here](https://www.wpguru.com.au/responsive-web-design-tips/click-event-working-ipad-iphone-ipod-fixed/)
There is also lot of other post about that issue if you want to google it out
=> Fix iPhone/iPad not triggering click event

lib/v-click-outside.js
I realized that  `find` is also no available on IE, so no need to try keeping any compatibility.
We may add a note about that in the README.
=> Revert "Remove use of findIndex to keep IE compatibility.".

package.json
The current released package don't include the latest updates. 
When publishing the package, the dist bundle is now builded.
=> Add a version hook to build package on publish.

lib/v-click-outside.js
This PR makes the touch/click event detection more cross-platform, to support non-Apple touch devices.
=> Use a more cross-platform touch detection method

lib/v-click-outside.js
This plugin wasn't working for me completely. My simplest as possible div that only has one `v-click-outside` directive wasn't emitting the handler function when clicking outside.
```html
<template>
<div v-click-outside="handleClickOutside">
...
</div>
</template>
<script>
export default {
methods: {
handleClickOutside () {
console.log('click') // Never triggered!
}
}
}
</script>
```
I debugged the plugin a bit, and it appears that it is because the handler is only getting registered on `directive.update` event, which never triggered in my case. So I also added it to `directive.bind` which will register the handler right away
=> Fix outside click when no update event were fired on component

README.md, lib/v-click-outside.js, test/v-click-outside.test.js
On mobile devices, the plugin always adds 2 events 'touchstart' 'click' to listener.
But in some cases, it might as well adding only 'click' event also on mobile devices.
For example, there are a menu has `v-click-outside` to closeing menu and a menu's icon has `@click` to toggling opening and closing about the menu.
In this case, touch the menu icon when the menu opened, once the menu is closed and it will soon be opened. Because 'touchstart' event is fired before 'click' event.
```
<template>
<span
class="menu-icon"
@click="toggleMenuOpeningClosing"
></span>
</template>
~~~~
<template>
<div
class="menu"
v-click-outside="closeMenu"
>
<menu-contents/>
</div>
</template>
```
To avoiding problems like this, I added a feature to enable to use 'notouch' modifier.
Using it, the plugin will add …
=> Add a feature to adding only click event on mobile devices

lib/v-click-outside.js
I added middleware as an optional binding to the directive signature. I haven't added tests yet, because I'm not sure of how the `bind` function works now. We need to either make an assumption that the first thing they pass will be the main click-outside callback, or we ask them to explicitly name it "onClick" so you can avoid having to use `Object.keys` to grab it. I think either way it would be a breaking change, right?
=> Add middleware function to directive binding

lib/v-click-outside.js
Hi, this should fix https://github.com/ndelvalle/v-click-outside/issues/39.
In the future, if you decide to access browser only globals in the global scope. please be mindful of SSR! 
Thanks
=> Fixes SSR errors by checking for window.

lib/v-click-outside.js, package-lock.json, test/v-click-outside.test.js
Hello!
I thought it would be nice to have an `active` switch on the config object, to basically prevent the handler from even being bound at all (for those situations where someone wants to avoid having too many handlers). It might be used like this:
```js
// pug: .thing(v-click-outside="computedConfig")
export default {
computed: {
computedConfig() {
return {
handler: this.handler,
active: this.active,
}
}
}
}
```
Also, I noticed while I was adding this that the `instances` list will grow without bound in the previous version of the code, because `unbind` didn't do anything to get rid of old instances. So I made a `destroyInstance` function that removes any existing event listeners and removes the item from the list.
Let me know how you feel about these changes!
=> Adds "active" functionality, closes instances memory leak.

lib/v-click-outside.js
This issue is actual when during SSR we use `global.window = { Vue }` for different workarounds. But `navigator` and `window.navigator` objects aren't existing.
=> Fix SSR issue when navigator is not defined

lib/v-click-outside.js, test/v-click-outside.test.js
Support anonymous binding better. Skip unnecessary updates and make `removeEventListener` work.
[https://github.com/ndelvalle/v-click-outside/issues/34](https://github.com/ndelvalle/v-click-outside/issues/34)
=> Support anonymous binding better

src/v-click-outside.js
This check prevents possible memory leaks for detached elements. This case could happen with async data, when the unbind function runs before the timeout.
=> After timeout, if el has already been unbound, do not attach event-listener

src/v-click-outside.js
I deleted the code `event.target! == el`. The reason is as follows:
- For `path.indexOf(el)`
If `el` is not in `event.path`，indicates that the click occurred outside `el`
- For `!el.contains(event.target)`
If `event.target` is not a descendant element of `el` or `el` itself，indicates that the click occurred outside `el`
Therefore, the additional judgment of `event.target! == el` is not needed.
(Forgive my poor english 😂)
=> Remove redundant judgments

README.md, example/src/views/Home.vue, src/v-click-outside.js
Following the discussion, closes https://github.com/ndelvalle/v-click-outside/issues/220. 
- adds docs on programatic usage, using `scopedSlots` as usecase.
- Includes demo at `example/` and `codesandbox` live example.
- Side-effect: ran `prettier` on `v-click-outside.js`, to ensure I could start dev server for the `example/` code
Changes to the code proposed on #1 were basically sugaring/shortcut imports  an as such was dismissed in favour o destructing the methods straight from `directive` imported object.
=> Docs: programatic usage

README.md, example/src/views/Home.vue, src/v-click-outside.js, test/v-click-outside.test.js
Attempt to close #80 with iframe click detection workaround.
Clicks on iframe don't bubble, so they are undetected by our `document.documentElement` listeners. Workarounds in the SO threads and dev internet fall into 3 categories:
1. add pseudo-elements cover ups on iframes, blocking click on iframe content but still bubbling document click;
1. wrap iframes on an extra <div> and capture the click on it;
1. `window.onblur` + `document.activeElement` combo;
The last one seemed the less intrusive:
- it doesn't block clicks on iframe content itself;
- it doesn't add extra DIVs which could cause layout issues;
- it keeps performance impact to a minimum;
The gist is that a click on an iframe will move `focus` to it. Since iframe has its own `window` our main app window will `blur`: on that …
=> fix: iframe click detection

example/src/views/Home.vue, src/v-click-outside.js
closes #232,
Making `onFauxIframeClick` a little bit smarter by checking if the iframe that triggered the `blur` event is inside the `v-click-outside` element, preventing `handler` execution in that case.
=> Fix/232 exclude iframes inside element from detectIframe mechanism

src/v-click-outside.js
Under certain conditions IE11 throws an error, indicating that it can't access tagName of activeElement.
For me it happens, when I'm closing a modal. Then activeElement is null.
In this PR I've just added a null check to prevent undefined access.
=> IE11 fix: Added check for activeElement

README.md, src/v-click-outside.js, test/v-click-outside.test.js
Proposal to add support of capture option to support click detection on elements using stopPropagation method.
If some element uses stopPropagation() method for click event, this directive doesn't trigger. Using explicit capture for these elements solves the issue.
=> Proposal to add support of capture option

package.json, src/v-click-outside.js
Hello!
Thank you, I always use the awesome library.
Event.path is deprecated on Chrome since about May 3rd.
https://chromestatus.com/feature/5726124632965120
But Internet Explorer has only Event.path.
I tried that it works with both browsers.
fix #533
=> fix: Don't use deprecated Event.path if composedPath() exists
